name: "New Entry"
description: "Suggest a new entry to the dictionary"
title: "[New Entry]: "
labels: ["new entry"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new entry to the dictionary!
  - type: input
    attributes:
      label: Lemma
      description: "What is the headword for the new entry?"
      placeholder: "example: cochlea"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Word class
      description: "What is the word class or part-of-speech of the new entry?"
      options:
        - n/a (for phrases, etc.)
        - adj. (adjective)
        - adv. (adverb)
        - conj. (conjunction)
        - f. (feminine noun)
        - interj. (interjection)
        - m. (masculine noun)
        - n. (neuter noun)
        - praep. (preposition)
        - pron. (pronoun)
        - v. (verb)
    validations:
      required: true
  - type: input
    attributes:
      label: English Translations
      description: "What are the English translations for the new entry?"
      placeholder: "example: snail"
    validations:
      required: false
  - type: input
    attributes:
      label: German Translations
      description: "What are the German translations for the new entry?"
      placeholder: "example: Schnecke"
    validations:
      required: false
  - type: input
    attributes:
      label: References
      description: "What are the references for the new entry?"
      placeholder: "example: Lewis&Short"
    validations:
      required: false
