name: "New Entry"
description: "Suggest a new entry to the dictionary"
title: "[New Entry]: "
labels: ["new entry"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new entry to the dictionary!
  - type: input
    attributes:
      label: Lemma
      description: "What is the headword for the new entry?"
      placeholder: "example: cochlea"
    validations:
      required: true
  - type: input
    attributes:
      label: Forms
      description: "What are the forms for the new entry?"
      placeholder: "example: -ae"
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Word class
      description: "What is the word class or part-of-speech of the new entry?"
      options:
        - n/a (for quotes, compound noun, etc.)
        - adj. (adjective)
        - adv. (adverb)
        - conj. (conjunction)
        - f. (feminine noun)
        - interj. (interjection)
        - m. (masculine noun)
        - n. (neuter noun)
        - praep. (preposition)
        - pron. (pronoun)
        - v. (verb)
    validations:
      required: true
  - type: input
    attributes:
      label: Variants
      description: "What are the variants, if any?"
      placeholder: "example: coclea"
    validations:
      required: false
  - type: input
    attributes:
      label: Notes
      description: "What are additional information, like grammar details or usage, for the new entry?"
      placeholder: "example: acc. sg. -im"
    validations:
      required: false
  - type: input
    attributes:
      label: Etymology
      description: "What is the etymology?"
      placeholder: "example: < gr. κοχλίας"
    validations:
      required: false
  - type: textarea
    attributes:
      label: Translations
      description: "What are the translations for the new entry?"
      placeholder: "example: snail        Schnecke"
  - type: input
    attributes:
      label: Derivatives
      description: "What are the derivatives, if any?"
      placeholder: "example: cochleatus, cochleola"
    validations:
      required: false
  - type: dropdown
    attributes:
      label: References
      description: "What are the references for the new entry?"
      multiple: true
      options:
        - Blaise
        - Chevin
        - DMLBS
        - Du Cange
        - Gaffiot
        - DMNES
        - Georges
        - Lewis&Short
        - LLN
        - LML
        - Niermeyer
        - OLD
        - Orbis latinus
        - PONS
        - PECS
        - Stowasser
        - Vicipaedia
